name: Build WEmulate frontend
on: push
jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: build/